SELECT * FROM nurse;
SELECT * FROM treatment;
SELECT * FROM doctor;
SELECT * FROM bed;
SELECT * FROM performs;
SELECT * FROM patient;
SELECT * FROM patient_report;
SELECT * FROM examination;
SELECT * FROM treated_by;
